// <auto-generated />
namespace NotWikiHow_.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Ihateinstruction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ihateinstruction));
        
        string IMigrationMetadata.Id
        {
            get { return "202110200141315_I hate instruction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
