// <auto-generated />
namespace NotWikiHow_.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ahhhhhh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ahhhhhh));
        
        string IMigrationMetadata.Id
        {
            get { return "202110200355446_ahhhhhh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
